// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:54120f08-f053-4fb4-9788-4b05da6fd252",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_F5ApbORB7",
    "aws_user_pools_web_client_id": "4t1irnu39qvr2k3v01slslap7b"
};


export default awsmobile;
